{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "1a2c8fc1_eca60547",
        "filename": "sc/qa/uitest/calc_tests9/tdf115933.py",
        "patchSetId": 3
      },
      "lineNbr": 29,
      "author": {
        "id": 1000179
      },
      "writtenOn": "2021-09-10T09:02:07Z",
      "side": 1,
      "message": "Why do you need this try/except part ?",
      "revId": "276e34f14c824e17683c8ff734d575cee50166ed",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d7632ad5_d7441681",
        "filename": "sc/qa/uitest/calc_tests9/tdf115933.py",
        "patchSetId": 3
      },
      "lineNbr": 29,
      "author": {
        "id": 1001967
      },
      "writtenOn": "2021-09-10T09:56:51Z",
      "side": 1,
      "message": "An error message is displayed, if Calc doesn\u0027t accept the password: The password is incorrect. The file cannot be modified.\n(click OK, and then click Cancel in password dialog)",
      "parentUuid": "1a2c8fc1_eca60547",
      "revId": "276e34f14c824e17683c8ff734d575cee50166ed",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4db09242_a2f6c7e7",
        "filename": "sc/qa/uitest/calc_tests9/tdf115933.py",
        "patchSetId": 3
      },
      "lineNbr": 29,
      "author": {
        "id": 1000179
      },
      "writtenOn": "2021-09-10T10:02:51Z",
      "side": 1,
      "message": "why would be the password be incorrect? The expected behaviour is the password to be correct. if it\u0027s incorrect and an error dialog is prompted, then the test will fail, that\u0027s why the try/except block is not needed, or am I missing something ?",
      "parentUuid": "d7632ad5_d7441681",
      "revId": "276e34f14c824e17683c8ff734d575cee50166ed",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "44706290_7bfd97bd",
        "filename": "sc/qa/uitest/calc_tests9/tdf115933.py",
        "patchSetId": 3
      },
      "lineNbr": 29,
      "author": {
        "id": 1001967
      },
      "writtenOn": "2021-09-10T12:22:32Z",
      "side": 1,
      "message": "I didn\u0027t know the test will fail, if an error dialog is prompted. The test without the try/except block stopped on my computer, if the password was incorrect.",
      "parentUuid": "4db09242_a2f6c7e7",
      "revId": "276e34f14c824e17683c8ff734d575cee50166ed",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615"
    }
  ]
}